CREATE DATABASE IF NOT EXISTS rosdb DEFAULT CHARACTER SET utf8mb4;

USE rosdb;

-- LiDAR 센서 데이터 테이블
CREATE TABLE IF NOT EXISTS lidardata (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ranges JSON NOT NULL,
  `when` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action VARCHAR(20) NOT NULL
);